### ISSUE TITLE
Deployment of custom app

### ISSUE THREAD

**Issue by creniq** [labpano/pilot-open-api#1]
Hello Labpano developers:

We are evaluating the Pilot Era camera for use in our operations. Our plan is to develop a custom app and we are currently building a prototype. Once that's finished, we will need a way to manage the lifecycle of the custom app, including initial deployment and updates. What would be the best way to handle this? There is no Google Play Store on the camera, so we cannot distribute/update the app through the app store. The only way seems to be using the adb tool to sideload the app. However, this is not ideal, as people who would be doing this are non-technical people.  

I'll appreciate any suggestions you may have. Thanks!

**Comment by forestlin1212** [comment]
Hi, @creniq  thank you for using Pilot Open API.
Please update the Pilot OS to 5.13.0.  We have introduced a function of installing apps in 5.13. PilotOS supports PC or mobile phone to upload apk files through the LAN to install Apps. Users can install apk on Pilot even if they are not developer.

This is not a perfect distribute solution, but it can solve your problem.

**Comment by creniq** [comment]
@forestlin1212 Thank you for the reply. Yes the suggested solution works well!
