### ISSUE TITLE
OSC API Support

### ISSUE THREAD

**Issue by creniq** [labpano/pilot-open-api#2]
Is there any plan to add support of Google Open Spherical Camera API to the SDK?

**Comment by zero-zzxx** [comment]
The current camera supports google OSC (part of the function), if it does not meet your needs, you can contact technical support(support@labpano.com) to get the customized OSC protocol usage document.

**Comment by creniq** [comment]
@zero-zzxx Thank you for the reply. I have contacted technical support. Hope to hear from them soon.

**Comment by creniq** [comment]
This is the reply I received from support@labpano.com, regarding OSC:

"
I hope you are doing great.
We have Pilot Open API, you can sign up for the Pilot ID and become a developer on the website: accounts.labpano.com

Should you have any questions, feel free to contact me for further assistance.
"

This does not answer my question. Obviously I'm already a developer, and have access to Pilot Open API. The problem I'm having is that I don't see OSC support in the API.

Please advise on how to obtain this "customized OSC protocol usage document" and I would really appreciate that.

**Comment by forestlin1212** [comment]
Hi @creniq , We put the document here  [pilot-control-protocol](https://github.com/labpano/pilot-control-protocol)

**Comment by creniq** [comment]
Thank you very much. I will take a look.

**Comment by creniq** [comment]
Hi @forestlin1212 

I have reviewed the document you provided. It is helpful. However, I did not find a way to achieve what I want to achieve. We are building a custom app that runs on the Pilot camera. We have another app running on a separate mobile device (an iPhone or an Android phone), and we'd like to have this app communicate with the Pilot camera, to launch our custom app.

It seems that we will need a new command through the http://x.x.x.x:8080/osc/commands/execute interface, to launch custom apps. Perhaps a command called "camera.startActivity", and with an intent string as parameter. Is this possible for you to add?

Thank you!

**Comment by forestlin1212** [comment]
ohoh, Pilot Control Protocol is used to control the built-in function of Pilot camera, which cannot control the developer's app. 

Add an activity interface cannot meet your needs. Your App may have many functions need to communicate with mobile phone. 

I think the best way is,  you have to develop the function of communicate with mobile phone in your Pilot camera side App.

**Comment by beforescaling** [comment]
What are the pixel formats that Labpano pilot one can work with?
Is any of the below acceptable?



  | I420 =(1)
  | NV21 =(3)
  |  
  | TEXTURE_2D =(10)
  | TEXTURE_OES =(11)

THANKS!

**Comment by dnzeek** [comment]
@forestlin1212 
Using the "camera.listFiles" command with the "fileType": "all" parameter only returns a list of JPG files. How can we get it to return the list of videos?

Thank you

**Comment by zero-zzxx** [comment]
> @forestlin1212 Using the "camera.listFiles" command with the "fileType": "all" parameter only returns a list of JPG files. How can we get it to return the list of videos?
> 
> Thank you

This is related to [pilot control protocol](https://github.com/labpano/pilot-control-protocol).
The Pilot Go App is also using this protocol, and no similar problems are found.
Please check again according to the document. Specifically, port 8080 is used.

**Comment by dnzeek** [comment]
> > @forestlin1212 Using the "camera.listFiles" command with the "fileType": "all" parameter only returns a list of JPG files. How can we get it to return the list of videos?
> > Thank you
> 
> This is related to [pilot control protocol](https://github.com/labpano/pilot-control-protocol). The Pilot Go App is also using this protocol, and no similar problems are found. Please check again according to the document. Specifically, port 8080 is used.

Port 8080 causes other problems. Please see issue posted in [pilot control protocol](https://github.com/labpano/pilot-control-protocol)
