### ISSUE TITLE
photoSample stitching issue

### ISSUE THREAD

**Issue by creniq** [labpano/pilot-open-api#3]
Hello labpano developers:

It appears that the photoSample has stitching issues - I have tried this sample as is without any modification. The resulting photos appear to be highly distorted. Can you please take a look? Thanks.

**Comment by zero-zzxx** [comment]
Can you provide photo files? If it's not convenient to send files, please contact technical support separately（ support@labpano.com ）。

**Comment by creniq** [comment]
@forestlin1212 Yes, I will provide some samples shortly. Note that I'm using the stock photoSample included in the SDK, without modifications.

**Comment by creniq** [comment]
Please see this example [https://drive.google.com/file/d/1-S7A8GBbbZI6Yv-gWUGOSzzWBMi4VOz_/view?usp=sharing](url)

You can clearly see mismatch along the stitching lines.

**Comment by creniq** [comment]
It appears the problem was fixed by the commit on Jan 13. I upmerged and no longer have this issue.
